### ISSUE TITLE
[BUG] Fail to run `azd up` 

### ISSUE THREAD

**Issue by Menghua1** [Azure-Samples/cosmos-db-nosql-python-quickstart#17]
### Description

When running `azd up`, it failed and docker needs to be started, but the readme.md does not mention installing and starting docker. The specific error message is as follows:
![image](https://github.com/user-attachments/assets/08f04d33-15cc-4099-a238-6a2ee4d3022c)

### Repro steps

1. Run `azd auth login`.
2. Run `azd init --template cosmos-db-nosql-dotnet-quickstart`.
3. Run `azd up`.

### Expected behavior

`azd up` can be run successfully.

### Environment

1. Azd version: azd version 1.10.3 (commit 0595f33fe948ee6df3da492567e3e7943cb9a733)
2. OS: Windows
3. Templates:
- https://github.com/azure-samples/cosmos-db-nosql-dotnet-quickstart 
- https://github.com/azure-samples/cosmos-db-nosql-python-quickstart 
- https://github.com/azure-samples/cosmos-db-nosql-nodejs-quickstart
- https://github.com/azure-samples/cosmos-db-nosql-java-quickstart
- https://github.com/azure-samples/cosmos-db-nosql-go-quickstart

@hemarina and @seesharprun for notification.

**Comment by seesharprun** [comment]
I'm reworking the readme to have far less steps and to call out the Docker requirement.

**Comment by seesharprun** [comment]
This has been fixed by adding a pre-req to the readme

**Comment by Menghua1** [comment]
It has been fixed, I will close this issue.
