### ISSUE TITLE
[BUG] Fail to load web page after running `azd up`

### ISSUE THREAD

**Issue by Menghua1** [Azure-Samples/cosmos-db-nosql-python-quickstart#18]
### Description

After running `azd up`, click the web link in the log, the page failed to load with the following error:
![image](https://github.com/user-attachments/assets/eb8e5338-dc76-49df-acc4-117446fca385)

### Repro steps

1. Run `azd auth login`.
2. Run `azd init --template cosmos-db-nosql-python-quickstart`.
3. Run `azd up`.
4. Click the web link.

### Expected behavior

The web page can be loaded successfully after running `azd up`.

### Environment
1. Azd version: azd version 1.10.3 (commit 0595f33fe948ee6df3da492567e3e7943cb9a733)
2. OS: Windows
3. Templates: 
- https://github.com/azure-samples/cosmos-db-nosql-python-quickstart 
- https://github.com/azure-samples/cosmos-db-nosql-nodejs-quickstart

@hemarina and @seesharprun for notification.

**Comment by seesharprun** [comment]
This is a transient bug I'm seeing with ACA related to websocket ports. I'm switching the deployment to App Service to see if that permanently resolves this port issue.

**Comment by seesharprun** [comment]
This has been fixed by setting up WebSocket polling
