### ISSUE TITLE
[BUG] Fail to run `azd pipeline config --provider github`

### ISSUE THREAD

**Issue by Menghua1** [Azure-Samples/cosmos-db-nosql-python-quickstart#19]
### Description

When running `azd pipeline config --provider github`, add `azure-dev.yml` as prompted, the workflow of `CodeQL Advanced` fails. The specific error message is as follows:
![image](https://github.com/user-attachments/assets/8e3d70e6-0572-422b-8ed8-ddd6591be05f)
![image](https://github.com/user-attachments/assets/74df55cc-0de6-45cc-8c8b-be45334d21cf)

### Repro steps

1. Run `azd auth login`.
2. Run `azd init --template cosmos-db-nosql-dotnet-quickstart`.
3. Run `azd up`.
4. Run `azd pipeline config`.
5. Click the pipeline status link.

### Expected behavior

`azd pipeline config --provider github` can be run successfully.

### Environment
1. Azd version: azd version 1.10.3 (commit 0595f33fe948ee6df3da492567e3e7943cb9a733)
2. OS: Windows
3. Templates: 
- https://github.com/azure-samples/cosmos-db-nosql-dotnet-quickstart 
- https://github.com/azure-samples/cosmos-db-nosql-python-quickstart 
- https://github.com/azure-samples/cosmos-db-nosql-nodejs-quickstart 
- https://github.com/azure-samples/cosmos-db-nosql-java-quickstart
- https://github.com/azure-samples/cosmos-db-nosql-go-quickstart

@hemarina and @seesharprun for notification.

**Comment by seesharprun** [comment]
I'm going to add a default pipeline configuration for GitHub to these templates. They previously didn't include this.

**Comment by seesharprun** [comment]
This pipeline file has now been added to all the samples

**Comment by Menghua1** [comment]
@seesharprun According to the latest code test, a default pipeline configuration for GitHub has been added, but when running `azd pipeline config --provider github`, the current issue still exists, and there is a new issue. The detailed information of the two issues is as follows:

1. `CodeQL Advanced`
![image](https://github.com/user-attachments/assets/c9a18c6b-ca46-418e-9b16-0d9ff969b4e5)
2. `.github/workflows/azure-dev.yml`
![image](https://github.com/user-attachments/assets/939639d4-d828-4a3c-b2d7-d65469db9248)

### Environment
1. Azd version: azd version 1.10.3 (commit 0595f33fe948ee6df3da492567e3e7943cb9a733)
2. OS: Windows
3. Templates: 
- https://github.com/azure-samples/cosmos-db-nosql-dotnet-quickstart 
- https://github.com/azure-samples/cosmos-db-nosql-python-quickstart 
- https://github.com/azure-samples/cosmos-db-nosql-nodejs-quickstart 
- https://github.com/azure-samples/cosmos-db-nosql-java-quickstart
- https://github.com/azure-samples/cosmos-db-nosql-go-quickstart

**Comment by seesharprun** [comment]
I'll research why CodeQL is running in the fork. Thanks for the heads-up about this.

**Comment by seesharprun** [comment]
I'll also look at why the pipeline configuration is failing.

This is an AZD resource group deployment (not subscription), so I suspect there's a missing env variable.

**Comment by seesharprun** [comment]
I recently updated CodeQL's pipeline so it won't run in anyone's fork.

I also updated the GitHub pipeline. I'm testing the GitHub pipeline later today to verify that it works as expected.

**Comment by seesharprun** [comment]
Both are not fixed in all five repositories:

- [x] CodeQL action will run but skip the job on forks. It will only run the job on upstream repositories.
- [x] I updated the GitHub pipeline to support the resource group deployment. I tested it against the samples.
