### ISSUE TITLE
[BUG] Fail to run and debug locally

### ISSUE THREAD

**Issue by Menghua1** [Azure-Samples/cosmos-db-nosql-python-quickstart#20]
### Description

**Describe the issue:**
According to the [Run and Debug Locally](https://learn.microsoft.com/azure/developer/azure-developer-cli/debug?pivots=ide-vs-code) documentation test, clicking `Run and Debug` in the activity bar, there is no corresponding debugger and the page is as follows:
![image](https://github.com/user-attachments/assets/235b2a4a-ba96-4d4f-b9eb-8c3492d11a85)
![image](https://github.com/user-attachments/assets/92bb47d3-355d-4420-898c-5c160714080d)
In addition, click F1 and selecting `Task: Run Task`, there are no tasks to choose from, the page is as follows:
![image](https://github.com/user-attachments/assets/ead8f374-b616-4cd2-819b-c463a6cd71b8)

### Repro steps

1. Run `azd auth login`.
2. Run `azd init --template cosmos-db-nosql-dotnet-quickstart`.
3. Run `azd up`.
4. Click  `Run and Debug` (or click F1 -> selecting `Task: Run Task`).

### Expected behavior

Running and debugging locally can succeed.
### Environment
1. Azd version: azd version 1.10.3 (commit 0595f33fe948ee6df3da492567e3e7943cb9a733)
2. OS: Windows
3. Templates: 

- https://github.com/azure-samples/cosmos-db-nosql-dotnet-quickstart 
- https://github.com/azure-samples/cosmos-db-nosql-python-quickstart 
- https://github.com/azure-samples/cosmos-db-nosql-nodejs-quickstart 
- https://github.com/azure-samples/cosmos-db-nosql-java-quickstart 
- https://github.com/azure-samples/cosmos-db-nosql-go-quickstart

@hemarina and @seesharprun for notification.

**Comment by seesharprun** [comment]
There's a few solutions to this that will be split across multiple PRs:

- .NET
  - The instructions have been updated to be more concise on how to debug for C#
- Node.js
  - The instructions have been updated to be more concise on how to debug for JavaScript or TypeScript
- Python/Java/Go
  - These steps will be removed from the readme as we don't have a way to "write back" to the provider.
  
I'll associate each PR as they are generated.

**Comment by Menghua1** [comment]
In the Readme.md of the latest `.NET`, `Node.js` templates, the test instructions related to `run and debug locality` have been deleted. Do these templates no longer support `run and debug locally`?

**Comment by seesharprun** [comment]
You can technically run the templates locally, but they don't have the ability to write back settings like .NET and Node.js templates have.

So yes, I removed the instructions from Python, Go, and Java for simplicity.
